Repository PlatziMaster/platzimaster.github.io, pull requests merged in 2020-03, with the labels that each got.

#3 Add a creativity blog post
  content/2020/2003-desbloquea-tu-creatividad.md
  src/components/layout.js
  src/styles/components/layout.css
Labels: blogpost

#5 Add a new blogpost
  content/2020/2103-como-colaborar-en-github.md
  package-lock.json
  package.json
Labels: blogpost

#7 Adding article 2103 Explota la oportunidad de tu vida
  content/2020/2103-Explota-la-oportunidad-de-tu-vida.md
Labels: blogpost

#8 Adding post 2103 Mejorar nuestro HTML y CSS con EMMET
  content/2020/0903-hello-world.md
  content/2020/2103-Mejorar-nuestro-HTML-y-CSS-con-EMMET.md
Labels: blogpost

#9 [Add] Post guia-platzi-master
  content/2020/2103-guia-platzi-master.md
Labels: blogpost

#10 Corrección de Typos
  content/2020/2103-guia-platzi-master.md
Labels: blogpost

#6 I added a post related comedy and story telling for presentations and…
  content/2020/2103-el-poder-del-humor-en-tu-presentacion.md
Labels: blogpost

#14 Edition and spell check to posts 0903 and 2003.
  content/2020/0903-hello-world.md
  content/2020/2003-desbloquea-tu-creatividad.md
Labels: blogpost

#15 La emocion del llamado
  content/2020/2203-la-emocion-del-llamado-a-platzimaster.md
Labels: blogpost

#16 [FIX] misspelling
  content/2020/2103-Mi-experiencia-platzi-master.md
Labels: wontfix

#17 JavaScript primitive data types
  content/2020/2203-JavaScript-primitive-data-types.md
Labels: blogpost

#18 Blog de habilidades blandas
  content/2020/2303-Habilidades-blandas-que-todo-lider-necesita.md
Labels: blogpost

#19 New feature script newpost
  README.md
  bin/newpost.js
  package.json
Labels: enhancement

#20 0324 ¿Tú negocio es escalable?
  bin/newpost.js
  content/2020/0324-Tu-negocio-es-escalable.md
Labels: blogpost

#22 Post: Tips de buenas prácticas para la escritura de código
  content/2020/0326-buenas-practicas-para-la-escritura-de-codigo.md
Labels: blogpost

#23 Articulo Andres Alba
  content/2020/0327-the-science-of-how-to-engage-your-custo.md
Labels: blogpost

#24 Cómo colaborar en proyectos open source
  content/2020/2703-contribute-open-source.md
Labels: blogpost
